#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${GOUT_DB_USER} WITH ENCRYPTED PASSWORD '${GOUT_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE gout_prod TO ${GOUT_DB_USER};
EOSQL
